### ISSUE TITLE
Microsoft Defender found Trojan: "Win32/Sirefef!cfg" in "real-world_ccsr.ckpt"

### ISSUE THREAD

**Issue by KannManMachen** [kijai/ComfyUI-CCSR#23]
Affected elements:

containerfile: C:\Users\USERNAME\Desktop\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\models\checkpoints\real-world_ccsr.ckpt

file: C:\Users\USERNAME\Desktop\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\models\checkpoints\real-world_ccsr.ckpt -> archive/data/919

**Comment by kijai** [comment]
It's a false positive, just in case I went through the file and there are bunch of unused training data included, besides the state_dict (which is just weights) there is just this info:
![image](https://github.com/kijai/ComfyUI-CCSR/assets/40791699/63bccc13-4f43-422f-a88e-33b76d089cfc)

However to put everyone's mind at ease, and to save disk space I pruned and converted the weights only:
https://huggingface.co/Kijai/ccsr-safetensors/tree/main

Seems to work as direct replacement for the node.

**Comment by KannManMachen** [comment]
Thanks a lot for clarification and for giving us safetensor files :)

Im curious – do you have any idea why Microsoft Defender was claiming the checkpoint as affected?
